name: ledger
version: "1.0.0"
config-version: 2
profile: ledger

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
target-path: target
clean-targets: [target, dbt_packages]

models:
  ledger:
    staging:
      +materialized: view
    marts:
      +materialized: table
